### ISSUE TITLE
When I run elasticsearch, another elasticserch is killed

### ISSUE THREAD

**Issue by flatcoke** [docker-library/elasticsearch#165]
I'm testing for cluster on docker , but when I run elasticsearch, another elasticserch is killed. There are two containers for each individual elasticsearch, Therefore I did testing without any link or port connection between two containers, but there was still the same result

Thanks for reading

**Comment by tianon** [comment]
I would guess you're running out of RAM -- Elasticsearch tries to allocate quite a lot by default, so two instances running is very likely to starve out even a semi-beefy node.

**Comment by flatcoke** [comment]
@tianon 
Absolutely it goes hand in hand with memory. After I saw your comment, I tried to work on another environment which performance is better than before, therefore It worked. 
But I want to know what how to avoid this problem, if i can

Thanks a lot

**Comment by tianon** [comment]
@flatcoke you can try playing with different values in `-e ES_JAVA_OPTS="-Xms512m -Xmx512m"`, but there's no guarantee that it will work (and different workloads within Elasticsearch will likely have different requirements)

I'm going to go ahead and close this since it's not really an issue, but more a question of successful configuration for tight environments -- for further questions, I'd recommend reaching out on [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
