### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by sugumarworkspace** [docker-library/elasticsearch#179]
After starting the ES Instance, the below menitoned task is running with high CPU usage peaking more than 100%. Is there any additional setup to be done or what is the best configuration for ES?

/docker-java-home/jre/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInit+

**Comment by tianon** [comment]
I'm not seeing the command you've referenced as a recommended way to start Elasticsearch -- where did that come from?  Is that the generated command from running `bin/elasticsearch` in the image?

I believe https://www.elastic.co/guide/en/elasticsearch/reference/master/jvm-options.html is the upstream documentation you're looking for on what specific Java parameters are recommended.

In my own experience, Elasticsearch is pretty resource-heavy, so it wouldn't surprise me if 2GB is not even close to sufficient for heavy workloads.

Since this doesn't appear to be something we can solve generically in the image (the parameters we provide to Elasticsearch are pretty stock from the Elasticsearch download itself), I'm going to close.
