### ISSUE TITLE
pid failure preventing startup with ports forwarded

### ISSUE THREAD

**Issue by bisoldi** [docker-library/elasticsearch#62]
When starting docker elasticsearch with the following command
`run elasticsearch -p 9200:9200 -p 9300:9300 --name es -Des.node.name="TestNode"`

I get the following exception:

    {1.7.3}: pid Failed ...
    FileNotFoundException[9300:9300 (Permission denied)]
    java.io.FileNotFoundException: 9300:9300 (Permission denied)
	    at java.io.FileOutputStream.open0(Native Method)
	    at java.io.FileOutputStream.open(FileOutputStream.java:270)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
            at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	    at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:194)
	    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)

If I run the following:
`run elasticsearch --name es -Des.node.name="TestNode"`

It starts up just fine, but the ports are obviously not exposed, which I need because the application accessing it is not a docker image and is remote.

This is using the elasticsearch image directly from Dockerhub.

**Comment by mkeshav** [comment]
I am facing the same issue

**Comment by yosifkit** [comment]
Mapped ports need to be sent to docker, not to the process running inside docker, so they need to come before the image name.

```console
$ docker run -p 9200:9200 -p 9300:9300 --name es elasticsearch -Des.node.name="TestNode"
```

**Comment by bisoldi** [comment]
Wow....I can't believe that was the problem.  I've never seen ordering of arguments change the execution of the process, but.....learn a new thing every day.

Thanks!

**Comment by yosifkit** [comment]
No problem! :smile: Order matters on commands more often than you think :wink:, like `git` (`git add -p` vs `git -p add`).  Everything after the image that you are running gets sent as arguments to the entrypoint or executed directly if there is no entrypoint.  CenturyLink has a pretty good explanation of [CMD and ENTRYPOINT](https://labs.ctl.io/dockerfile-entrypoint-vs-cmd/).  If the first argument looks like a flag, the entrypoint for elasticsearch sets permissions for `/usr/share/elasticsearch/data` and then passes all its arguments along to the `elasticsearch` executable, otherwise it just runs it, so that `docker run -it elasticsearch bash` just works.
