### ISSUE TITLE
Clarify "official

### ISSUE THREAD

**Issue by markwalkom** [docker-library/elasticsearch#66]

**Comment by yosifkit** [comment]
> The Docker Official Repositories are a curated set of Docker repositories that are promoted on Docker Hub.
> https://docs.docker.com/docker-hub/official_repos/

We would definitely be interested if upstream elastic would be interested in maintaining their Official Images or even involved in any way :smile:.  We have some info on how to take over: https://github.com/docker-library/official-images#maintainership.  The gist is get involved.  The sentry image was transferred quite quick since they were already involved (https://github.com/getsentry/docker-sentry/issues/19).

**Comment by psftw** [comment]
@markwalkom please reach out to me directly (ps@docker.com) if you have any particular concerns after reading up on the links above.  It's not uncommon for an upstream vendor to be involved in both an Official Repository and also maintain their own releases under an organization account on DockerHub (i.e. ``neo4j`` and ``neo4j/neo4j``).  Our engineering team has endorsed Found, and we are looking to strengthen the relationship in other ways in the near future.

**Comment by markwalkom** [comment]
Sorry, I kinda let this one slide!

I think (not to be taken as the official truth ;)) we would be interested in eventually managing this as an official image, but we've just had a few people hit us up directly because of the "official" tag and have made the assumption we already are.

That last part is just want could be clarified.

(Apologies for the crap OP too)

**Comment by jasontedor** [comment]
In light of #160 and the discussion there, I think that this issue can be closed now?
