### ISSUE TITLE
Can't chown files inside container while running on boot2docker

### ISSUE THREAD

**Issue by Hariador** [docker-library/elasticsearch#69]
Running it an issue where we cannot run an elasticsearch container on boot2docker running on OSX while bind mounting the data and config directories.  Our previous work around was to drop the chown and gosu lines from the docker_entrypoint.sh and run as root in the container since this was just a local dev environment.  However, the latest dockerfile image is now checking if elasticsearch us running as root and bailing if it is.  The new hacky fix is to run 'usermod -u 1000 elasticsearch' before chown in the entry point. From reading previous similar issues, it appears that there was a plan to use environment variables to let elasticsearch optionally run as root, but that no longer appears to be the case.  Is there a better less fragile way to get this running?

**Comment by yosifkit** [comment]
The bailing while running as root is something elastic added in the 2.0 release.  The `usermod` is one way to fix it for boot2docker; you could also modify the entrypoint to use user id `1000` instead of `elasticsearch` on the chown and gosu lines.

We were still unsure on whether to include the option of what UID/GID to run as because it would be inconsistent when images like mysql do the step down themselves through an option in a config.
